name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: ls -la

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - run: npm install

      - run: npm test

  docker-build-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: anugrah28
          password: dckr_pat_--Cw1fXqA7sRqS-MSmw-yRbo57Q

      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            anugrah28/nodejs-demo-app:latest
            anugrah28/nodejs-demo-app:${{ github.sha }}