https://github.com/AnugrahMassey/Automate-Code-Deployment-Using-CI-CD-Pipeline.gitname: CI/CD Pipeline for Node.js App

on:
  push:
    branches: [ "main" ]  
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3


      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"  

     
      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

  docker-build-push:
    needs: build-and-test  
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

     
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.anugrah28 }}
          password: ${{ secrets.dckr_pat_--Cw1fXqA7sRqS-MSmw-yRbo57Q }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .  
          push: true  
          tags: |
            ${{ secrets.anugrah28 }}/nodejs-demo-app:latest
            ${{ secrets.dckr_pat_--Cw1fXqA7sRqS-MSmw-yRbo57Q }}/nodejs-demo-app:${{ github.sha }}